--기존 테이블, 시퀀스 삭제
DROP TABLE MEMBER;
DROP TABLE BOARD1;
DROP TABLE BOARD1_REPLY;
DROP SEQUENCE BOARD1_SEQ_NUM;
DROP SEQUENCE BOARD1_REPLY_SEQ_NUM;

--MEMBER TABLE 생성
CREATE TABLE MEMBER(
	ID VARCHAR2(20),-- PRIMARY KEY,
	PW VARCHAR2(20),
	NAME VARCHAR2(10)
);

--BOARD1의 글번호 SEQUENCE 생성
CREATE SEQUENCE BOARD1_SEQ_NUM INCREMENT BY 1 START WITH 1;

--BOARD1 TABLE 생성
CREATE TABLE BOARD1(
	NO NUMBER(5),-- PRIMARY KEY,
	ID VARCHAR2(20),-- FOREIGN KEY
	TITLE VARCHAR2(100),
	BODY VARCHAR2(999),
	WR_DATE VARCHAR2(10)
);

--BOARD1의 REPLY SEQUENCE 생성
CREATE SEQUENCE BOARD1_REPLY_SEQ_NUM INCREMENT BY 1 START WITH 1;

--BOARD1의 REPLY TABLE 생성
CREATE TABLE BOARD1_REPLY(
	REPLY_NO NUMBER(5),--PRIMARY KEY
	NO NUMBER(5),--FOREIGN KEY
	ID VARCHAR2(20),
	REPLY VARCHAR2(500),
	RE_DATE VARCHAR2(10)
);

--계정 추가
INSERT INTO MEMBER VALUES(
	'rlatpdbs@gmail.com', 'ksy1469', '김세윤'
);

--BOARD1 테스트 내용 추가
INSERT INTO BOARD1 VALUES(
	BOARD1_SEQ_NUM.NEXTVAL, 'rlatpdbs@gmail.com', 'test', 'test', SYSDATE
);

--BOARD1_REPLY 테스트 내용 추가
INSERT INTO BOARD1_REPLY VALUES(
	BOARD1_REPLY_SEQ_NUM.NEXTVAL, 1, 'rlatpdbs@gmail.com', 'TEST 댓글', SYSDATE
);

COMMIT;
